version: '3'
services:
  credential-issuer:
    build: .
    ports:
      - 3000:3000
    environment:
      - VERIFIER_BASE_URL=http://verifier:8080
    volumes:
      - .:/code
    command: ["npm", "run", "start-watch"]

  verifier:
    build: ./verifier
